export const FETCH_UPLOADS_REQUEST = 'FETCH_UPLOADS_REQUEST';
export const FETCH_UPLOADS_SUCCESS = 'FETCH_UPLOADS_SUCCESS';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';

export const DELETE_UPLOAD_REQUEST = 'DELETE_UPLOAD_REQUEST';
export const DELETE_UPLOAD_SUCCESS = 'DELETE_UPLOAD_SUCCESS';

export const UPDATE_UPLOAD_REQUEST = 'UPDATE_UPLOAD_REQUEST';
export const UPDATE_UPLOAD_SUCCESS = 'UPDATE_UPLOAD_SUCCESS';

export const ADD_TO_REQUEST = 'ADD_TO_REQUEST';
export const ADD_TO_SUCCESS = 'ADD_TO_SUCCESS';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
